### PR TITLE
clean matlab folder

### PR DESCRIPTION
**Pull request by Remi-Gau**
Trying to address issue #112 about organizing the matlab code folder
- moved files into sub-folders as suggested in the issue
- change scripts so they still run
- run scripts
- update the content of the template folder with the output

One question: I did put the script to create the JSON for fmap into the func folder. Does that make sense or should we have into a specific fmap folder?

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@dorahermes I can't assign reviewers but I suspect you would be the likely one to look into this. :-)

**Comment by dorahermes** [comment]
Thanks @Remi-Gau ! It seems that fmap has a different folder in all scenarios [here](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#fieldmap-data) so I believe that is the only correction

**Comment by Remi-Gau** [comment]
> Thanks @Remi-Gau ! It seems that fmap has a different folder in all scenarios [here](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#fieldmap-data) so I believe that is the only correction

Yup that's what I thought after the fact but just wanted to make sure we agreed on this. :-)

**Comment by dorahermes** [comment]
lgtm :-)

**Comment by dorahermes** [comment]
resolved issue #112 Cleaning up the Matlab code

**Pull request merged**
