### PR TITLE
Update EpilepsyClassification.tsv

### PR DESCRIPTION
**Pull request by tpatpa**
Changed column names to snake_case (#132 )

### CODE REVIEW

**Comment by dorahermes** [comment]
Thanks Tal! Would you be able to change only these 4 headers in the .json file such that these match the .tsv? (not all the entries, only these 4)

This seems kind of a chicken and egg problem though, does the .json format lead or does the .tsv lead... Let's assume for now that the .tsv leads only for the column header.

**Comment by tpatpa** [comment]
Sure, make sense.. Done!
Thanks @dorahermes !

**Comment by dorahermes** [comment]
Thanks @tpatpa ! I am merging this and this will close issue #132

**Comment by Remi-Gau** [comment]
@all-contributors please add @tpatpa for code

**Pull request merged**
