### PR TITLE
Add pet template

### LINKED ISSUE #196: Add PET Template
Now that BEP 009 has gone through it seems like as good a time as any to update the templates to include a PET example.

Proposed update will add the following to the `templates/sub-01/ses-01/` folder:
```bash
pet
├── sub-01_ses-01_recording-autosampler_blood.json
├── sub-01_ses-01_recording-autosampler_blood.tsv
├── sub-01_ses-01_recording-manual_blood.json
├── sub-01_ses-01_recording-manual_blood.tsv
├── sub-01_ses-01_task-FullExample_pet.json
└── sub-01_ses-01_task-ShortExample_pet.json
```

### PR DESCRIPTION
**Pull request by bendhouseart**
Fixes #196 

I'm wondering if I've included too many recording files, but I was aiming for completeness in the spirit of the other templates I'd seen for MR, EEG, etc.

### CODE REVIEW

**Comment by dorahermes** [comment]
This is great! thank you

**Comment by dorahermes** [comment]
@Remi-Gau this is adding a full pet session in the templates, and looks good to me, I'll let you merge

**Comment by Remi-Gau** [comment]
This looks great. 
Will try to cross check that in detail tomorrow: it comes at the right time, as I might need to bidsify some tuto PET data.

Thank you so much @bendhouseart !

**Comment by bendhouseart** [comment]
It's become a, pet, project of mine recently :roll_eyes:

Thanks for taking a look!

**Comment by Remi-Gau** [comment]
> It's become a, pet, project of mine recently roll_eyes
> 
> Thanks for taking a look!

I am so upset by that pun... Mostly because I did not think of it first. :1st_place_medal:

**Comment by melanieganz** [comment]
Hi @Remi-Gau, can you please let us know if you want changes before merging this?

**Comment by Remi-Gau** [comment]
hey @bendhouseart @melanieganz 

Could not push directly on top of this PR, so I sent a PR on @bendhouseart branch instead: merging it should update this PR.

In brief: it adds some matlab scripts to create the tsv and json instead of creating them manually.

I also "updated" some file names: will try to stick to PascalCase for labels in filenames.

All of that is not mentioned anywhere in our contributing, so I could not expect you to know this. Will update that in a separate PR (and do some cleaning at the same time).

**Comment by melanieganz** [comment]
Thanks so much, @Remi-Gau! Then I'll let you and @bendhouseart handle this.

**Comment by bendhouseart** [comment]
@Remi-Gau things look gtg on my end, other then the failed matlab checks ;P

**Comment by Remi-Gau** [comment]
OK I will merge despite the whole thing not being green: the incriminate files are not quite related to the original purpose of this PR. 
I will do the code cleaning in another PR. :-)

**Pull request merged**
