### PR TITLE
FIX - updated links to material elsewhere

### PR DESCRIPTION
**Pull request by robertoostenveld**
- replaced INCF by bids-standard
- updated the link to the spec (not the old PDF any more)
- corrected capitalization for "bids-starter-kit" (all lower case)

### CODE REVIEW

**Comment by dorahermes** [comment]
lgtm, thank you!

**Comment by dorahermes** [comment]
@KirstieJane what is the current policy on merging in the bids-starter-kit?

**Comment by robertoostenveld** [comment]
@KirstieJane could you have a look at this? Especially the link to the old PDF is problematic, since it does not reflect all the work that went into the conversion to https://bids-specification.readthedocs.io/

**Comment by dorahermes** [comment]
This has been submitted 1 week ago and these are all necessary changes. I will merge this now. Rules for how/when to approve and merge will have to be addressed in a separate issue.

**Comment by dorahermes** [comment]
Ah, thanks Kirstie for approving!

**Comment by KirstieJane** [comment]
Just clicked merge @dorahermes. I think for small changes like this one person's review is fine. 

I don't anticipate big conflicts in the starter kit, I doubt there will be things that people will find particularly contentious! So I don't think we need any greater governance than someone taking a look and saying YAY!

**Comment by dorahermes** [comment]
Ok, I agree!

**Comment by Remi-Gau** [comment]
@all-contributors please add @robertoostenveld for bug

**Pull request merged**
