### PR TITLE
Add more details to session

### PR DESCRIPTION
**Pull request by SamGuay**
* Add details discussed in #265.
* Also added a link to the specific comment regarding EEG considerations from our discussion.

### CODE REVIEW

**Comment by SamGuay** [comment]
I can build it locally so not sure what is wrong regarding the build-book fail.

Also, I couldn't find a new link to replace [✖] http://www.fieldtriptoolbox.org/reference/data2bids/, it seems to be gone from that website..

**Comment by Remi-Gau** [comment]
> Also, I couldn't find a new link to replace [heavy_multiplication_x] http://www.fieldtriptoolbox.org/reference/data2bids/, it seems to be gone from that website..

Maybe best to link to the code itself? 

https://github.com/fieldtrip/fieldtrip/blob/release/data2bids.m

Also those are not changes you have made, so you did not break it so I would not worry about it.

**Review by Remi-Gau — APPROVED** [review]
OK I Will merge this and try to solve the problems in another PR.

**Comment by Remi-Gau** [comment]
@SamGuay updated jupyter book version in #267 and that fixed it. :magic_wand:

**Pull request merged**
