### PR TITLE
BIDS Philosophy: Add a minder map with minimal text to highlight that lots of other standards used

### PR DESCRIPTION
**Pull request by yarikoptic**
For some reason svg seems to not render for me by github here, so here is a png preview:

image

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@yarikoptic what software do you use to edit the minp map? Or is that a format that most mind map editors can work with? 
Depending on the answer: we may want to make a note of that somewhere in case future generations (or me in 6 months) want to edit it.

**Comment by yarikoptic** [comment]
eh, I added detail in the commit message for https://github.com/bids-standard/bids-starter-kit/pull/294/commits/b958009b1a656487900a6f406ee9935318323bf4 but forgot in the PR:  Minder app: https://github.com/phase1geo/Minder
(on Debian systems  apt install minder  and then run
com.github.phase1geo.minder)

**Comment by yarikoptic** [comment]
@Remi-Gau et al - ping on this PR.  Please guide me or just merge it ;)

**Comment by Remi-Gau** [comment]
ha.
sorry when I first saw this PR I remembered: "Need to take the time to see how to improve on this." And then I never got back to it.
Let's merge for now and iterate if anyone gets suggestions.

**Pull request merged**
