### PR TITLE
WIP: add warning for importing JSONio lib for matlab/octave

### PR DESCRIPTION
**Pull request by Remi-Gau**
Regarding the issue #119

I am tempted to keep the original call to the function jsonwrite and simply add a warning if it fails with a link to the library.

Other possibility: call the bids.util.jsonencode function from the matlab-bids library which would also make sense because this is a bids related issue.

Any thought? @gllmflndn 

Once we have decided I will change all the example scripts accordingly.

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Also why is git / github showing ALL the lines as having been modified ?

**Comment by KirstieJane** [comment]
> 
> 
> Also why is git / github showing ALL the lines as having been modified ?

I think this is a windows line ending thing. I set this up when I install git....but it can be changed. Check out http://www.edwardthomson.com/blog/git_for_windows_line_endings.html for a longer discussion.

**Comment by Remi-Gau** [comment]
Thanks will have a look.

I was on windows and now back on linux (finally!!!) but pretty much copied my whole github/folder from there. So I suspect something is afoot there indeed.

Will get back to you when I have sorted this!

**Comment by Remi-Gau** [comment]
Closing this for now. Will reopen a new one once I have this line ending problem under control.

**Pull request closed without merging**
